### ISSUE TITLE
请问这个SpEL中的returnObject是什么呀

### ISSUE THREAD

**Issue by mynameisny** [wpcfan/spring-boot-tut#4]
https://github.com/wpcfan/spring-boot-tut/blob/433603e810dbde7d08b987bf0d95e0b7f20a79ce/src/main/java/dev/local/user/UserController.java#L54
我按照您的代码执行之后，其它的都是正常的，如果这里returnObject如果写成：
```
@PreAuthorize(value = "returnObject.username == principal.username or hasRole('ROLE_ADMIN')")
```
就会报一个异常：
```
org.springframework.expression.spel.SpelEvaluationException: EL1007E: Property or field 'username' cannot be found on null

**Comment by wpcfan** [comment]
PreAuthorize 表示在方法执行前检查，那时候还没有返回值啊，这 returnedObject就是你这个方法返回的对象啊
